Repository simplabs/qunit-dom-codemod, pull requests merged in 2018-04, with the labels that each got.

#7 package.json: Add `engines` metadata
  package.json
Labels: enhancement

#8 replace PATH with ./tests
  README.md
Labels: documentation

#15 Skip transformation for jQuery extension selectors
  __testfixtures__/qunit-dom-codemod/equal-find-length.input.js
  __testfixtures__/qunit-dom-codemod/equal-find-length.output.js
  __testfixtures__/qunit-dom-codemod/equal-find-text-trim.input.js
  __testfixtures__/qunit-dom-codemod/equal-find-text-trim.output.js
  __testfixtures__/qunit-dom-codemod/equal-find-text.input.js
  __testfixtures__/qunit-dom-codemod/equal-find-text.output.js
  __testfixtures__/qunit-dom-codemod/equal-find-value.input.js
  __testfixtures__/qunit-dom-codemod/equal-find-value.output.js
  __testfixtures__/qunit-dom-codemod/ok-find.input.js
  __testfixtures__/qunit-dom-codemod/ok-find.output.js
  qunit-dom-codemod.js
Labels: bug

#16 Transform `findWithAssert()` expression to `assert.dom(...).exists()`
  __testfixtures__/qunit-dom-codemod/find-with-assert.input.js
  __testfixtures__/qunit-dom-codemod/find-with-assert.output.js
  qunit-dom-codemod.js
Labels: enhancement

#17 Add support for transforming to `.isChecked()`
  __testfixtures__/qunit-dom-codemod/checked.input.js
  __testfixtures__/qunit-dom-codemod/checked.output.js
  qunit-dom-codemod.js
Labels: enhancement

#18 Add support for `isDisabled()` and `isRequired()` assertions
  __testfixtures__/qunit-dom-codemod/disabled.input.js
  __testfixtures__/qunit-dom-codemod/disabled.output.js
  __testfixtures__/qunit-dom-codemod/required.input.js
  __testfixtures__/qunit-dom-codemod/required.output.js
  qunit-dom-codemod.js
Labels: enhancement
